name: lotto_app
description: "A new Flutter project."

publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6 # สำหรับเรียก Web API
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.webp
